console.time('Your code took');
console.log("Hello");
// alert("Hi");
var a = 10;
console.log(a);
console.log(10);
console.table({jay:'this', marks:140});
// console.clear();
// console.time();
console.timeEnd('Your code took');
console.assert(500 > 179, 'This is not possible');